#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_instance="0.0.1"
  jq -n --arg instance "$ver_instance" '{instance: $instance}'
}

version "$@"
